name: coins_flutter_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.2.0
  mobx: ^2.5.0
  get: ^4.7.2
  flutter_mobx: ^2.3.0
  dio: ^5.8.0+1
  fl_chart: ^0.70.2
  intl: ^0.18.1
  path_provider: ^2.1.1
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  mobx_codegen: ^2.7.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - .env
